package br.com.trabalhofontes;

public enum Token {
    BLOCKCOMMENT,NATWP,FLOATWP,COMMENT, STRING,NOEQ, EQ, ADD, MUL, MINUS, DIV, ID, INT, ERROR, WHITE, INPUTCHAR, SPACECHAR, LINECHAR, FLOAT, LEFTPARENT, RIGHTPARENT,
    IF, ELSE, END, OR, MAJOR, LESS, EQLESS, EQMAJOR, RANGE, WHILE,RIGHTBRACK,LEFTBRACK,NAT,ARROW,NO,AND, LINEBREAK
    
}